#
# Makefile for the touchscreen drivers.
#

obj-$(CONFIG_TOUCHPANEL_GOODIX_GT9886) += GT9886/

obj-$(CONFIG_TOUCHPANEL_GOODIX) += goodix_common.o
obj-$(CONFIG_TOUCHPANEL_GOODIX) += goodix_tool.o
obj-$(CONFIG_TOUCHPANEL_GOODIX) += gtx8_tools.o
